### ISSUE TITLE
Running commentator on file in a subdirectory results in a FileNotFoundError

### ISSUE THREAD

**Issue by jaltmayerpizzorno** [emeryberger/commentator#5]
I _think_ missing subdirectories in `backup` might be the cause.
```
$ commentator src/slipcover/bytecode.py 
src/slipcover/bytecode.py ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━  50% 0:00:12
Traceback (most recent call last):
  File "/opt/homebrew/bin/commentator", line 5, in <module>
    from commentator.__main__ import main
  File "/opt/homebrew/lib/python3.10/site-packages/commentator/__main__.py", line 148, in <module>
    main()
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/commentator/__main__.py", line 146, in main
    asyncio.run(do_it(api_key, language, progress, file))
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/lib/python3.10/site-packages/commentator/__main__.py", line 66, in do_it
    await asyncio.gather(*tasks)
  File "/opt/homebrew/lib/python3.10/site-packages/commentator/__main__.py", line 44, in commentate_one_file
    with open(os.path.join(save_path, file.name), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'backup/src/slipcover/bytecode.py'
```

**Comment by emeryberger** [comment]
Thanks, should be fixed now.
