### ISSUE TITLE
AttributeError: module 'ast_comments' has no attribute 'unparse'

### ISSUE THREAD

**Issue by wentao585** [emeryberger/commentator#8]
`xxx@yyy:~/OpenSource_ws/ChatDBG/test$` commentator testme.py 

Traceback (most recent call last):
  File "/home/wbi/.local/bin/commentator", line 5, in <module>
    from commentator.__main__ import main
  File "/home/wbi/.local/lib/python3.8/site-packages/commentator/__main__.py", line 149, in <module>
    main()
  File "/home/wbi/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/wbi/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/wbi/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wbi/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/wbi/.local/lib/python3.8/site-packages/commentator/__main__.py", line 147, in main
    asyncio.run(do_it(api_key, check, language, progress, file))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/wbi/.local/lib/python3.8/site-packages/commentator/__main__.py", line 67, in do_it
    await asyncio.gather(*tasks)
  File "/home/wbi/.local/lib/python3.8/site-packages/commentator/__main__.py", line 30, in commentate_one_file
    the_code = commentator.extract_function_source(code, func_name)
  File "/home/wbi/.local/lib/python3.8/site-packages/commentator/commentator.py", line 339, in extract_function_source
    return ast.unparse(extract_function_ast(program_str, function_name))
AttributeError: module 'ast_comments' has no attribute 'unparse'
xxx@yyy:~/OpenSource_ws/ChatDBG/test$ more testme.py 
def tryme(x):
    count = 0
    for i in range(100):
        if x / i > 2:
            count += 1
    return count
`

**Comment by emeryberger** [comment]
Please update to the latest version (0.2.8) and try again. Thanks.

`python3 -m pip install -U python-commentator`

**Comment by emeryberger** [comment]
My result for the example:

```
def tryme(x: float) -> int:
    """
    The function counts the number of integers from 1-99 (inclusive) that divide `x` such that the quotient is more than 2.
    
    Args:
        x: A floating point number.
        
    Returns:
        The number of integers from 1 to 99 (inclusive) that, when dividing `x`, give a result greater than 2.
    """
    count = 0
    for i in range(1, 100):
        if x / i > 2:
            count += 1
    return count
```
